### ISSUE TITLE
Logger: Log-Levels in different environments

### ISSUE THREAD

**Issue by johannwagner** [EmbeddedEnterprises/autobahnkreuz#9]
We need to set different log levels in different environments.

This should be a **runtime** environment variable, which should state the maximum log level.

Possible values: 
* ERROR
* WARN
* INFO
* DEBUG

**Comment by jwuensche** [comment]
We should also add the `CRITICAL` level, since it is provided in go-logging.

**Comment by johannwagner** [comment]
Yep, do it.

**Comment by martin31821** [comment]
Fixed with #10
